Repository Banana-Byte-Entertainment/My-City-Turned-Dystopian-So-I-Started-Vandalising-It, pull requests merged in 2025-07, with the labels that each got.

#37 Create GitHub Action
  .github/workflows/main.yml
Labels: others

#42 Added A temp Map
  Assets/Models/hoverboardmap.fbx
  Assets/Models/hoverboardmap.fbx.meta
  Assets/Scenes/SampleScene.unity
Labels: modelling, ui

#49 Added build profiles
  .github/workflows/main.yml
  Assets/Settings/Build Profiles.meta
  Assets/Settings/Build Profiles/Linux.asset
  Assets/Settings/Build Profiles/Linux.asset.meta
  Assets/Settings/Build Profiles/Windows 32-bit.asset
  Assets/Settings/Build Profiles/Windows 32-bit.asset.meta
  Assets/Settings/Build Profiles/Windows 64-bit.asset
  Assets/Settings/Build Profiles/Windows 64-bit.asset.meta
  Assets/Settings/Build Profiles/Windows ARM.asset
  Assets/Settings/Build Profiles/Windows ARM.asset.meta
  Assets/Settings/Build Profiles/macOS Universal.asset
  Assets/Settings/Build Profiles/macOS Universal.asset.meta
  Assets/Settings/DefaultVolumeProfile.asset
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/MultiplayerManager.asset
  ProjectSettings/Packages/com.unity.dedicated-server/ContentSelectionSettings.asset
  ProjectSettings/Packages/com.unity.dedicated-server/MultiplayerRolesSettings.asset
  ProjectSettings/ProjectSettings.asset
Labels: others

#61 Update Map
  Assets/Scenes/Map.unity
Labels: ui

#64 Fix animations
  Assets/Animations/Player/HoverboardController.controller
  Assets/Animations/Player/PlayerController.controller
Labels: player movement, modelling

#67 Title screen
  Assets/Prefabs/TransitionManager.prefab
  Assets/Prefabs/TransitionManager.prefab.meta
  Assets/Scenes/Test.meta
  Assets/Scenes/Test/SampleScene.unity
  Assets/Scenes/Test/SampleScene.unity.meta
  Assets/Scenes/Test/SampleScene2.unity
  Assets/Scenes/Test/SampleScene2.unity.meta
  Assets/Scenes/Test/Start.unity
  Assets/Scenes/Test/Start.unity.meta
  Assets/Scenes/Test/rail-movement.unity
  Assets/Scenes/Test/rail-movement.unity.meta
  Assets/Scenes/TitleScreen.unity
  Assets/Scenes/TitleScreen.unity.meta
  Assets/Scripts/Graffiti/GraffitiCanvas.cs
  Assets/Scripts/MainMenu.cs
  Assets/Scripts/TransitionManager.cs
  Assets/Scripts/TransitionManager.cs.meta
  Assets/UI/Sprites/TitleScreen.png
  Assets/UI/Sprites/TitleScreen.png.meta
  Assets/UI/Sprites/TitleScreenText.png
  Assets/UI/Sprites/TitleScreenText.png.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: ui, optional

#70 General cleanup
  .gitignore
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  README.md
Labels: optional, others

#82 General Fix
  Assets/Materials/Player.meta
  Assets/Materials/Player/BlueGlow.mat
  Assets/Materials/Player/BlueGlow.mat.meta
  Assets/Materials/Player/GreenGlow.mat
  Assets/Materials/Player/GreenGlow.mat.meta
  Assets/Materials/Player/PlayerJacket.mat
  Assets/Materials/Player/PlayerJacket.mat.meta
  Assets/Models/PlayerModel 1.fbx.meta
  Assets/Resources.meta
  Assets/Scripts/PauseMenu.cs
  Assets/Textures/JacketDesign.png
  Assets/Textures/JacketDesign.png.meta
Labels: modelling, optional
